version: "3"
services:
  grafana:
    image: grafana/grafana:latest
    ports:
    - 3000:3000
    environment:
    - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - ./docker/data/grafana:/var/lib/grafana
  logstash:
    image: docker.elastic.co/logstash/logstash:6.3.2
    volumes:
      - ./docker/data/logstash/data:/usr/share/logstash/data
      - ./docker/data/logstash/logs:/usr/share/logstash/logs
      - ./docker/config/logstash/config:/usr/share/logstash/config
      - ./docker/config/logstash/pipeline:/usr/share/logstash/pipeline
    depends_on:
      - elasticsearch
    ports:
      - 9600:9600
      - 4560:4560
  kibana:
    image: docker.elastic.co/kibana/kibana:6.3.2
    ports:
      - 5601:5601
    environment:
        - ELASTICSEARCH_URL=http://elasticsearch:9200
    depends_on:
        - elasticsearch
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.3.2
    environment:
      - discovery.type=single-node
    volumes:
      - ./docker/data/elasticsearch:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300
  influxdb:
    image: influxdb:latest
    ports:
    - 8086:8086
    - 8083:8083
    - 2003:2003
    volumes:
    - ./docker/data/influx:/var/lib/influxdb
    environment:
      INFLUXDB_GRAPHITE_ENABLED: "true"
      INFLUXDB_ADMIN_ENABLED: "true"
      INFLUXDB_DB: "pub"
      INFLUXDB_ADMIN_USER: "admin"
      INFLUXDB_ADMIN_PASSWORD: "admin"
      INFLUXDB_USER: "user"
      INFLUXDB_USER_PASSWORD: "password"
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: "admin"
      POSTGRES_USER: "admin"
      POSTGRES_DB: "test"
    ports:
    - 5433:5432
  jaeger:
    image: jaegertracing/all-in-one
    ports:
    - "5775:5775/udp"
    - "6831:6831/udp"
    - "6832:6832/udp"
    - "5778:5778"
    - "16686:16686"
    - "14268:14268"
  zipkin:
    image: openzipkin/zipkin
    ports:
    - "9411:9411"

  rabbitmq:
    image: rabbitmq:3-management
    ports:
    - 15672:15672
    - 5672:5672
  bartender:
    build:
      context: .
      args:
        service: "bartender"
        version: "0.1.0"
    environment:
      RABBIT_HOST: "rabbitmq"
      RABBIT_PORT: 5672
      RABBIT_USERNAME: "guest"
      RABBIT_PASSWORD: "guest"
      RABBIT_EXCHANGES: "com.example.tap"
      RABBIT_RK: "water,water;soda,soda;coke,coke;"
      BARTENDER_QUEUE_NAME: "bartender"
      BARTENDER_EXCHANGE: "com.example.bartender"
      BARTENDER_RK: "drink.poured"
      CONSOLE_HOST: "http://console:9999"
      SERVICE_NAME: "bartender"
      INFLUX_DB_HOST: "influxdb"
      INFLUX_DB_PORT: 8086
      INFLUX_DB_NAME: "pub"
      INFLUX_DB_USERNAME: "user"
      INFLUX_DB_PASSWORD: "password"
      TRACE_TICK_INTERVAL: "10 seconds"
      TRACE_SAMPLING_PROBABILITY: "1"
      JAEGER_HOST: "jaeger"
      JAEGER_PORT: 14268
      ZIPKIN_HOST: "zipkin"
      ZIPKIN_PORT: 9411
      SIGAR_ENABLED: "false"
      JMX_ENABLED: "true"
      LOGSTASH_HOST: logstash
      LOGSTASH_PORT: 4560
    depends_on:
      - db
    ports:
    - 9000:9000
  console:
    build:
      context: .
      args:
        service: "console"
        version: "0.1.0"
    environment:
      DATABASE_HOST: "jdbc:postgresql://db:5432/test"
      DATABASE_USER: "admin"
      DATABASE_PASSWORD: "admin"
      BARTENDER_HOST: "http://bartender:9000"
      SERVICE_NAME: "console"
      INFLUX_DB_HOST: "influxdb"
      INFLUX_DB_PORT: 8086
      INFLUX_DB_NAME: "pub"
      INFLUX_DB_USERNAME: "user"
      INFLUX_DB_PASSWORD: "password"
      TRACE_TICK_INTERVAL: "10 seconds"
      TRACE_SAMPLING_PROBABILITY: "1"
      JAEGER_HOST: "jaeger"
      JAEGER_PORT: 14268
      ZIPKIN_HOST: "zipkin"
      ZIPKIN_PORT: 9411
      SIGAR_ENABLED: "false"
      JMX_ENABLED: "true"
      LOGSTASH_HOST: logstash
      LOGSTASH_PORT: 4560
    ports:
    - 9999:9999
    depends_on:
      - rabbitmq
      - db
  soda_tap:
    build:
      context: .
      args:
        service: "tap"
        version: "0.1.0"
    environment:
      TAP_DRINK: "soda_tap"
      RABBIT_HOST: "rabbitmq"
      RABBIT_PORT: 5672
      RABBIT_USERNAME: "guest"
      RABBIT_PASSWORD: "guest"
      TAP_RK: "soda"
      POUR_DURATION: "200 millis"
      TAP_EXCHANGE: "com.example.tap"
      TAP_QUEUE: "soda"
      BARTENDER_EXCHANGE: "com.example.bartender"
      BARTENDER_RK: "drink.poured"
      SERVICE_NAME: "tap"
      INFLUX_DB_HOST: "influxdb"
      INFLUX_DB_PORT: 8086
      INFLUX_DB_NAME: "pub"
      INFLUX_DB_USERNAME: "user"
      INFLUX_DB_PASSWORD: "password"
      TRACE_TICK_INTERVAL: "10 seconds"
      TRACE_SAMPLING_PROBABILITY: "1"
      JAEGER_HOST: "jaeger"
      JAEGER_PORT: 14268
      ZIPKIN_HOST: "zipkin"
      ZIPKIN_PORT: 9411
      SIGAR_ENABLED: "false"
      JMX_ENABLED: "true"
      LOGSTASH_HOST: logstash
      LOGSTASH_PORT: 4560
    depends_on:
      - rabbitmq
  coke_tap:
    build:
      context: .
      args:
        service: "tap"
        version: "0.1.0"
    environment:
      TAP_DRINK: "coke_tap"
      RABBIT_HOST: "rabbitmq"
      RABBIT_PORT: 5672
      RABBIT_USERNAME: "guest"
      RABBIT_PASSWORD: "guest"
      TAP_RK: "coke"
      POUR_DURATION: "200 milis"
      TAP_EXCHANGE: "com.example.tap"
      TAP_QUEUE: "coke"
      BARTENDER_EXCHANGE: "com.example.bartender"
      BARTENDER_RK: "drink.poured"
      SERVICE_NAME: "tap"
      INFLUX_DB_HOST: "influxdb"
      INFLUX_DB_PORT: 8086
      INFLUX_DB_NAME: "pub"
      INFLUX_DB_USERNAME: "user"
      INFLUX_DB_PASSWORD: "password"
      TRACE_TICK_INTERVAL: "10 seconds"
      TRACE_SAMPLING_PROBABILITY: "1"
      JAEGER_HOST: "jaeger"
      JAEGER_PORT: 14268
      ZIPKIN_HOST: "zipkin"
      ZIPKIN_PORT: 9411
      SIGAR_ENABLED: "false"
      JMX_ENABLED: "true"
      LOGSTASH_HOST: logstash
      LOGSTASH_PORT: 4560
    depends_on:
      - rabbitmq
  water_tap:
    build:
      context: .
      args:
        service: "tap"
        version: "0.1.0"
    environment:
      TAP_DRINK: "water_tap"
      RABBIT_HOST: "rabbitmq"
      RABBIT_PORT: 5672
      RABBIT_USERNAME: "guest"
      RABBIT_PASSWORD: "guest"
      TAP_RK: "water"
      POUR_DURATION: "200 millis"
      TAP_EXCHANGE: "com.example.tap"
      TAP_QUEUE: "water"
      BARTENDER_EXCHANGE: "com.example.bartender"
      BARTENDER_RK: "drink.poured"
      SERVICE_NAME: "tap"
      INFLUX_DB_HOST: "influxdb"
      INFLUX_DB_PORT: 8086
      INFLUX_DB_NAME: "pub"
      INFLUX_DB_USERNAME: "user"
      INFLUX_DB_PASSWORD: "password"
      TRACE_TICK_INTERVAL: "10 seconds"
      TRACE_SAMPLING_PROBABILITY: "1"
      JAEGER_HOST: "jaeger"
      JAEGER_PORT: 14268
      ZIPKIN_HOST: "zipkin"
      ZIPKIN_PORT: 9411
      SIGAR_ENABLED: "false"
      JMX_ENABLED: "true"
      LOGSTASH_HOST: logstash
      LOGSTASH_PORT: 4560
    depends_on:
      - rabbitmq